name: Run Test Script and Node Version

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "$SSH_PRIVATE_KEY"
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa your_server_ip >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        USER : ${{secrets.USER}}
        HOST : ${{secrets.HOST}}

    - name: Run test.sh on the server
      run: |
        ssh -i ~/.ssh/id_rsa USER@HOST '/home/ubuntu/scripts/test.sh'
      
    - name: Check Node.js version on the server
      run: |
        ssh -i ~/.ssh/id_rsa USER@HOST 'node -v'
