name: Run Script on Self-Hosted EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: self-hosted  # Ensure your self-hosted runner is properly configured

    steps:
    - name: Clear GitHub Actions cache
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git gc --aggressive --prune=all
      continue-on-error: true

#    - name: Checkout code
#      uses: actions/checkout@v3

    - name: Run script on EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@34.251.221.47 'bash -s' < /home/ubuntu/test.sh
      continue-on-error: true

    - name: Refresh SSH Connection
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@34.251.221.47 'exit'
      continue-on-error: true

    - name: Check server node version
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@34.251.221.47 'node -v'
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@34.251.221.47 'npm -v'
      continue-on-error: true
