name: Run Script on Self-Hosted EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: self-hosted  # Ensure your self-hosted runner is properly configured

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and run script
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        chmod 600 /home/ubuntu/test.sh  # Make sure your script is executable
        ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $EC2_USERNAME@$EC2_HOST "cd /home/ubuntu && ./test.sh"
    
    - name: Check Node.js version on EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        node_version=$(ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $EC2_USERNAME@$EC2_HOST "node -v")
        echo "Node.js version on EC2: $node_version"
